name: Check the source code
on: push
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
      - name: Install packages
        run: pnpm install
      - name: Prettier
        run: pnpm run format
      - name: Lint
        run: pnpm run lint
